name: Publish to npm

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version_and_publish:
    name: Generate and publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn
        
      - name: Launch testing
        run: yarn test
  
      - name: Build
        run: yarn build
        
      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
